title: MXHECTORVEGA
url: "https://mxhectorvega.github.io"
theme: jekyll-theme-minimal
  social_links:
    twitter: mxhectorvega
    github:  mxhectorvega
    facebook: mxhectorvega
    instagram: mxhectorvega
    youtube: mxhectorvega
    youtube_channel: mxhectorvega
    youtube_channel_name: mxhectorvega
    telegram: mxhectorvega
